name: helloworld_dart
description: A simple Dart web application
repository: https://github.com/willianpaixao/helloworld-dart
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.4
  dart_pre_commit: ^5.4.5
  lints: ^5.1.1
