name: Security Vulnerability Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Monday
    - cron: '0 0 * * 1'

permissions:
  security-events: write

jobs:
  docker-image-scan:
    name: Container Image Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t helloworld-dart:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'helloworld-dart:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  dart-dependency-scan:
    name: Dart Dependencies Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Get dependencies
        run: dart pub get

      - name: Run dependency-check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'helloworld-dart'
          path: '.'
          format: 'SARIF'
          out: 'dependency-check-report'
          args: >
            --enableExperimental
            --scan pubspec.lock

      - name: Upload dependency check results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'dependency-check-report/dependency-check-report.sarif'
